# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelBuddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('plan', models.CharField(max_length=255)),
                ('users', models.ManyToManyField(to='travelBuddy.User')),
            ],
        ),
    ]
